version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    restart: always
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: app
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
volumes:
  db_data:
